### ISSUE TITLE
Windows + English

### ISSUE THREAD

**Issue by cadop** [lemonhall/node_hi219m_imu_test_mac#1]
Do you have a demo for windows, or at least english explanation?

**Comment by lemonhall** [comment]
It's just an demo for my private use, So ..just few codes;

You can see code , about 50 lines , very simple ...

1、install driver for windows
2、install node.js
3、install dependencs
4、run code

**Comment by cadop** [comment]
The issue was the sensor giving data.length of 41, and your code says 36.  Maybe something changed recently.

**Comment by lemonhall** [comment]
Yes, the sensor programe change but it not update it's document
